spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # cj -> Connector Java    url: "jdbc:mysql://localhost:3306/qjxt?characterEncoding=UTF8&useSSL=false&serverTimezone=UTC"
    username: "root"
    password: "333531"
